#spring:
#  security:
#    user:
#      name: admin
#      password: 123456


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurityyideng
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
server:
  servlet:
    session:
      timeout: 1 #单位是分钟
